### PR TITLE
[master] Update GitHub Actions

### PR DESCRIPTION
**Pull request by mattmoor**
Copied from `https://github.com/knative-sandbox/.github/tree/master/workflow-templates`.
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by tcnghia** [comment]
@mattmoor  BUILD GHA seems to be broken ?
/hold

**Comment by mattmoor** [comment]
cc @dprotaso 

another one

**Review by tcnghia — APPROVED** [review]
/lgtm

**Pull request merged**
